"""empty message

Revision ID: c2d4a5e0e620
Revises:
Create Date: 2022-10-03 04:51:56.314035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d4a5e0e620'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('patient_status', sa.String(length=20), nullable=True),
    sa.Column('bed_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('medicine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicine_name', sa.String(length=150), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('rate', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient')
    op.drop_table('medicine')
    # ### end Alembic commands ###
